Repository Trapscendence/ft_transcendence, pull requests merged in 2021-11, with the labels that each got.

#32 Feature/login with 42
  .env_template
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/main.ts
  backend/src/schema.gql
  backend/src/session/decorator/user.decorator.ts
  backend/src/session/guard/gql.session.guard.ts
  backend/src/session/guard/session.guard.ts
  backend/src/session/session.controller.spec.ts
  backend/src/session/session.controller.ts
  backend/src/session/session.module.ts
  backend/src/session/strategy/ft.strategy.ts
  backend/src/users/users.resolver.ts
  backend/src/users/users.service.ts
  docker-compose.yaml
  package-lock.json
Labels: enhancement

#28 user-module 중간 pr
  backend/src/users/users.resolver.ts
Labels: enhancement

#49 feature/#47/subscription guard
  .env_template
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.spec.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.spec.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/decorator/gql-user.decorator.ts
  backend/src/auth/dto/jwt.dto.ts
  backend/src/auth/guards/gql-jwt.guard.ts
  backend/src/auth/guards/jwt.guard.ts
  backend/src/auth/strategies/ft.strategy.ts
  backend/src/auth/strategies/jwt.strategy.ts
  backend/src/auth/types/oauth.type.ts
  backend/src/channels/channels.resolver.ts
  backend/src/main.ts
  backend/src/session/guard/gql.session.guard.ts
  backend/src/session/guard/session.guard.ts
  backend/src/session/session.controller.ts
  backend/src/session/session.module.ts
  backend/src/session/strategy/google.strategy.ts
  backend/src/users/users.resolver.ts
  docker-compose.yaml
  frontend/src/index.tsx
Labels: enhancement

#51 fe/feature/#3/login-button
  docker-compose.yaml
  frontend/src/App.tsx
  frontend/src/components/ChannelList/ChannelList.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/components/Login/LoginContainer.tsx
  frontend/src/components/Login/index.ts
  frontend/src/index.tsx
  frontend/src/utils/RestrictRoute/RestrictRoute.tsx
  frontend/src/utils/cookieParser.ts
  frontend/src/utils/gqls.ts
  frontend/src/utils/popupWindowCenter.ts
  frontend/src/utils/responseModels.ts
Labels: enhancement

#67 be/feature/#61/channel role guard
  backend/src/auth/dto/jwt.dto.ts
  backend/src/auth/guards/jwt.guard.ts
  backend/src/channels/channels.resolver.ts
  backend/src/channels/channels.service.ts
  backend/src/channels/decorator/role.channel.decorator.ts
  backend/src/channels/decorators/channel-roles.decorator.ts
  backend/src/channels/guard/channel-role.guard.ts
  backend/src/channels/guard/role.channel.guard.ts
  backend/src/users/users.service.ts
Labels: feature

#71 be/refactor/#65/auth decorator
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/decorator/gql-user.decorator.ts
  backend/src/auth/decorator/public.decorator.ts
  backend/src/auth/decorator/user-id.decorator.ts
  backend/src/auth/guards/jwt.guard.ts
  backend/src/channels/channels.resolver.ts
  backend/src/users/users.resolver.ts
Labels: feature

#86 Feature/direct message jolim
  .env_template
  backend/src/app.module.ts
  database/Dockerfile
  docker-compose.yaml
  frontend/package-lock.json
  migration/Dockerfile
  migration/database.json
  migration/entrypoint.sh
  migration/migrations/20211116165651-grant-schema.js
Labels: feature

#85 (fix feature) #58 #66 #76 #80 #81
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/decorators/public.decorator.ts
  backend/src/auth/guards/jwt.guard.ts
  backend/src/auth/strategies/ft.strategy.ts
  backend/src/channels/channels.resolver.ts
  backend/src/channels/channels.service.ts
  backend/src/channels/classes/mutedusers.class.ts
  backend/src/channels/models/channel.model.ts
  backend/src/matchs/models/match.model.ts
  backend/src/users/decorators/user-id.decorator.ts
  backend/src/users/models/user.model.ts
  backend/src/users/users.resolver.ts
  backend/src/users/users.service.ts
  frontend/src/components/Channel/Channel.tsx
  frontend/src/components/Channel/Chatting/Chatting.tsx
  frontend/src/utils/gqls.ts
  frontend/src/utils/models.ts
  frontend/src/utils/schemaEnums.ts
Labels: bug, feature, improvement

#97 feature/channel
  .DS_Store
  backend/Dockerfile
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/decorators/public.decorator.ts
  backend/src/auth/guards/jwt.guard.ts
  backend/src/auth/strategies/ft.strategy.ts
  backend/src/channels/channels.resolver.ts
  backend/src/channels/channels.service.ts
  backend/src/channels/classes/mutedusers.class.ts
  backend/src/channels/guard/channel-role.guard.ts
  backend/src/channels/models/channel.model.ts
  backend/src/matchs/models/match.model.ts
  backend/src/users/decorators/user-id.decorator.ts
  backend/src/users/models/user.model.ts
  backend/src/users/users.resolver.ts
  backend/src/users/users.service.ts
  frontend/package-lock.json
  frontend/src/App.tsx
  frontend/src/components/Channel/Channel.tsx
  frontend/src/components/Channel/ChannelHeader/ChannelEditModal.tsx
  frontend/src/components/Channel/ChannelHeader/ChannelHeader.tsx
  frontend/src/components/Channel/Chatting/Chatting.tsx
  frontend/src/components/Channel/Chatting/ChattingMessage.tsx
  frontend/src/components/ChannelList/ChannelList.tsx
  frontend/src/components/ChannelList/ChannelListContents/ChannelCard.tsx
  frontend/src/components/ChannelList/ChannelListContents/ChannelListContents.tsx
  frontend/src/components/ChannelList/ChannelListHeader/ChannelCreateModal.tsx
  frontend/src/components/ChannelList/ChannelListHeader/ChannelListHeader.tsx
  frontend/src/components/Navigation/Navigation.tsx
  frontend/src/components/commons/ErrorAlert/ErrorAlert.tsx
  frontend/src/components/commons/LoadingBackdrop/LoadingBackdrop.tsx
  frontend/src/components/commons/MsgSnackbar/MsgSnackbar.tsx
  frontend/src/components/commons/MsgSnackbar/index.ts
  frontend/src/components/commons/NicknameMenu/ChannelNicknameMenu.tsx
  frontend/src/components/commons/NicknameMenu/NicknameMenu.tsx
  frontend/src/hooks/useInput.ts
  frontend/src/index.tsx
  frontend/src/utils/RestrictRoute/RestrictRoute.tsx
  frontend/src/utils/gqls.ts
  frontend/src/utils/handleError.ts
  frontend/src/utils/models.ts
  frontend/src/utils/responseModels.ts
  frontend/src/utils/schemaEnums.ts
  migration/Dockerfile
  migration/entrypoint.sh
Labels: bug, feature

#105 fix: Publish the updated user role #83
  backend/src/channels/channels.service.ts
  backend/src/channels/models/channel.model.ts
Labels: feature

#106 feat: Unmute after the mute time has passed #95
  backend/src/channels/channels.resolver.ts
  backend/src/channels/channels.service.ts
Labels: feature

#111 feat: Reverse proxy server #108
  .env_template
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/main.ts
  certbot/init-script.sh
  certbot/nginx.conf
  docker-compose.yaml
  frontend/src/App.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/index.tsx
  proxy/default.conf
Labels: feature

#110 fix: Create timeout callback function
  backend/src/channels/channels.service.ts
Labels: bug

#114 fix: No channel in muted_users is not an error
  backend/src/channels/channels.service.ts
  backend/src/channels/classes/mutedusers.class.ts
Labels: bug

#112 CM/feature/#108/Reverse proxy server
  .env_template
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/main.ts
  certbot/init-script.sh
  certbot/nginx.conf
  docker-compose.yaml
  frontend/src/App.tsx
  frontend/src/components/Login/Login.tsx
  frontend/src/index.tsx
  proxy/default.conf
Labels: feature

#117 fix: #95 #116
  backend/src/channels/channels.service.ts
Labels: bug

#140 feature/#138/profile image seyu
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/users/models/user.model.ts
  backend/src/users/users.resolver.ts
  backend/src/users/users.service.ts
  database/Dockerfile
  docker-compose.yaml
  migration/migrations/20211126114606-create-storage-user.js
  storage/package-lock.json
  storage/package.json
  storage/src/app.controller.spec.ts
  storage/src/app.controller.ts
  storage/src/app.module.ts
  storage/src/app.service.ts
  storage/src/database/database.module.ts
  storage/src/database/database.service.ts
  storage/src/database/pg-pool.factory.ts
  storage/src/logger.middleware.spec.ts
  storage/src/main.ts
  storage/src/session.guard.ts
  storage/src/utils/envs.ts
Labels: feature

#135 feature/#118/require channel password
  backend/src/app.module.ts
  backend/src/channels/channels.resolver.ts
  backend/src/channels/channels.service.ts
Labels: feature

#148 feature/#144/status
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/status/status.service.ts
  backend/src/utils/factories/graphql.factory.ts
Labels: feature
